repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0  # Use the sha / tag you want to point at
    hooks:
    - id: mypy
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.4
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: python
        args: [--fix, --exit-non-zero-on-fix]
        require_serial: true
      # Run the formatter.
      - id: ruff-format
